# See https://docs.bridgecrew.io/docs/integrate-with-gitlab-runner
# and https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html
variables:
  CHECKOV_IMAGE: "${REGISTRY_HOST}/bridgecrew/checkov:latest"
  CHECKOV_OPTS: "-o cli -o junitxml --repo-id $CI_PROJECT_PATH --prisma-api-url $PRISMA_API_URL"

.pcs_scan:
  stage: analyze
  allow_failure: true # True for AutoDevOps compatibility
  image:
    name: $CHECKOV_IMAGE
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  rules:
    # Same Pattern as SonarQube
    # Always scan on merges, do not scan if DISABLE_SCAN is set
    - if: $DISABLE_SCAN
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        BRANCH_OPTS: "--branch $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
      allow_failure: true
    - if: "$CI_COMMIT_TAG"
      variables:
        BRANCH_OPTS: "--branch $CI_COMMIT_TAG"
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_TAG == null && $CI_COMMIT_REF_NAME != "develop" && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
      variables:
        BRANCH_OPTS: "--branch $CI_COMMIT_REF_NAME"
      when: manual
      allow_failure: true
  script:
    - checkov $CHECKOV_OPTS $BRANCH_OPTS $CHECKOV_FRAMEWORK_OPTS --bc-api-key "$PRISMA_API_KEY" --output-file-path console,report\checkov\results.xml
  artifacts:
    reports:
      junit: report\checkov\results.xml
    paths:
      - report\checkov\results.xml
